name: WeirdGrenade
version: 1.0
website: https://github.com/xxyy/weirdgrenade
description: Allows players to fire weird grenades.

softdepend: [ItemRenamer]

main: io.github.xxyy.weirdgrenade.WeirdGrenadePlugin


